### ISSUE TITLE
bug in decode when string has punctiation

### ISSUE THREAD

**Issue by guilhermebr** [dineshappavoo/basex#9]
When decode a string with any punctuation basex crash.

ex:
basex.Decode("AeI.oU")

PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 9 [running]:
    /usr/local/go/src/runtime/panic.go:426 +0x4e9
math/big.(*Int).Mul(0xc82020cae0, 0xc82020cb00, 0x0, 0x0)
    /usr/local/go/src/math/big/int.go:156 +0x149
github.com/guilhermebr/pirat.as/backend/vendor/github.com/dineshappavoo/basex.Decode(0xc82020c125, 0x7, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/guilhermebr/pirat.as/backend/vendor/github.com/dineshappavoo/basex/basex.go:109 +0x4c4

**Comment by dineshappavoo** [comment]
@guilhermebr  - Thanks for finding the bug and fixing it. Merged the pull request.
